# Generated by Django 4.0.5 on 2022-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('genre', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
